### ISSUE TITLE
Include option to not send queries to the Anki browser window

### ISSUE THREAD

**Issue by soameshi** [animebook/animebook.github.io#20]
When Animebook Anki Export updates a card, I have it send queries to the Anki browser window to hide your card from the browser while it's being updated. This makes it so you don't get into weird scenarios where, because you're editing the card in realtime, Animebook can't update it since your changes overwrite anything Animebook tries to do.

However, I noticed on my Gnome 3 setup that this actually always brings the Anki browser window to the forefront (on Windows it'll only open the window if it's minimized). This is really annoying when you only have 1 monitor and want to fullscreen animebook, so I think it'd be best to have a "Don't do anything to the anki browser" option in the extension. It just needs to come with a warning that if you use the option, animebook can't update your latest card if you have it selected.

**Comment by psychodelicwasabi** [comment]
Here, it creates 4 new windows every time I update a card. Also, since we are at it, is there a way to make it so we can populate more than a single card in case we mine several words that will share the same sentence?

**Comment by soameshi** [comment]
That's, not good. Are they all Anki browsers? I run 3 browser queries to guarantee the new card shows up pre-selected, but I was probably relying on how a Windows Anki setup works too much.

Also, I have the code changes done for this option, so if you want to try it out you can download the repo and use the Chromium extension page's "Load Unpacked" option to try it out beforehand. You'd just need to point to the "extension" folder in the repo, since that's where it lives.

Otherwise, I'll try to release the next version of the extension within the next 2 weeks ( I need some time to test some other things with it).

**Comment by soameshi** [comment]
> is there a way to make it so we can populate more than a single card in case we mine several words that will share the same sentence?

Most likely not, since I don't want to clutter the UI with something that doesn't save much time and actually sounds risky depending on implementation e.g. you might want to update 2 cards but accidentally tell the extension to update 3.

**Comment by psychodelicwasabi** [comment]
> That's, not good. Are they all Anki browsers? I run 3 browser queries to guarantee the new card shows up pre-selected, but I was probably relying on how a Windows Anki setup works too much.

Yes, they are all Anki browser windows. By the way, it's only three, I had a browser window already opened at the time.

> Also, I have the code changes done for this option, so if you want to try it out you can download the repo and use the Chromium extension page's "Load Unpacked" option to try it out beforehand. You'd just need to point to the "extension" folder in the repo, since that's where it lives.
> 
> Otherwise, I'll try to release the next version of the extension within the next 2 weeks ( I need some time to test some other things with it).

Damn, I'll probably try that out since waiting 2 weeks for it is a bit too much... Although I'm not confident I can do it.


> Most likely not, since I don't want to clutter the UI with something that doesn't save much time and actually sounds risky depending on implementation e.g. you might want to update 2 cards but accidentally tell the extension to update 3.

I see. I had in mind the configurations to populate only if the field is empty, which is what I already use as a default, so that would (or should) avoid the accidental third card. But well, this is fine as well.

**Comment by psychodelicwasabi** [comment]
Just tried it out and it works, no more extra windows. However, how optimistic would you be about circumventing the need to keep the last card unselected in the future? Since new cards are usually not selected, that's not a big problem, but I'm curious.

**Comment by soameshi** [comment]
I can't do anything about it, really. By selecting the latest card, Anki detects that as you submitting updates to it (since you're editing it), so if an update comes in from Animebook, it gets immediately overwritten with what you have open in the editor pane.

At best maybe a fix in AnkiConnect could do something about it? Kinda outta my hands at that point though.
