### ISSUE TITLE
Search error each time I use the extension

### ISSUE THREAD

**Issue by kappitanKappa** [animebook/animebook.github.io#23]
First of all, great job, the workflow is fairly easy to set-up and it's stupid fast.
However, each time I use the extension, Anki throws an error saying the search isn't valid (though oddly enough, it seems to search correctly anyway, it just throws the error on top of it).
It would be great to add an option not to search at all, too.

**Comment by soameshi** [comment]
Is the error coming from the animebook page or anki? If it's anki, what version of anki are you using? Got a screenshot?

I'm going to add an option not to search at all in #20 by the way.

**Comment by kappitanKappa** [comment]
The error was coming from Anki, I was on ver. 2.1.22, updated to 2.1.40 and the error no longer appears, so I guess this thread is a bit useless now... I still attached a screenshot of the error just in case. Thanks!
![anki_err](https://user-images.githubusercontent.com/73838724/108637848-c5572c00-748c-11eb-83b3-9184d9511870.png)

**Comment by soameshi** [comment]
Oh, thanks! I did happen to notice a typing mistake in one of the queries I was sending to Anki, and it may have been coincidentally working in the later versions of Anki, but not in 2.1.22. I fixed it, so once I get a new release out, hopefully other people won't have to run into this.
