### ISSUE TITLE
Offline use with Anki export?

### ISSUE THREAD

**Issue by kuronari** [animebook/animebook.github.io#28]
I don't know if this is normal or an issue, but when using it offline (downloading the page to use offline) the button to Anki export doesn't show up.

**Comment by soameshi** [comment]
I have to enable the "Allow access to file URLs" option on the extension (same thing goes for yomichan) before it works on offline files.
![image](https://user-images.githubusercontent.com/20632064/112947442-0679d600-90f4-11eb-8c42-5c197e0fe424.png)

Is this the issue? Or is it something else?

**Comment by kuronari** [comment]
I totally missed that one. Thanks for the quick reply. Works fine now! :)
