### ISSUE TITLE
Browser extension doesn't detect video file when file is coming from another device on the network

### ISSUE THREAD

**Issue by cademcniven** [animebook/animebook.github.io#38]
I have my video files saved on a NAS and animebook is able to play them just fine. However, when I use the animebook browser extension to create anki cards, it gives me the error, "No video file found". Interestingly, this only happens on my windows machine -- I do the exact same thing on my laptop running linux and it works fine. 

I understand it's kinda my fault for using the app in an unintended way, and I also know I could just download the files locally (or just not make cards). However, I'd appreciate any help or ideas for how to get it working.

**Comment by soameshi** [comment]
I don't have a NAS to test this out with, but are there any errors in the dev console when you drop the video in?

**Comment by cademcniven** [comment]
Unfortunately there's not. BUT I think I found a solution (kind of). It seems like the issue only happens when I add the video file via the "browse" button. If I add the video by dragging it, it works just fine

**Comment by soameshi** [comment]
Oh, your extension might be out of date. What version do you have on your Windows machine? Anything released before October will probably run into this issue. See #37

**Comment by cademcniven** [comment]
That should be it! I have version 1.0.0 on my windows machine, which would explain why it works on my linux machine (I set it up more recently).
