### ISSUE TITLE
AutoHotKey

### ISSUE THREAD

**Issue by Hiwoyn** [animebook/animebook.github.io#42]
Hi, I love animebook. It helps me a lot in my learning journey. Thank you very much.

Could it be possible to have animebook at the start of the chrome tab name instead of just the file name?
![image](https://user-images.githubusercontent.com/35316996/147397851-efbcca1f-2c25-44e4-9052-04262b4e9867.png)
I'm using autohotkey to bind easy shortcuts on my mouse in most of my programs with an If statement for each window I'm currently using (for example, only Chrome: #IfWinActive, ahk_exe chrome.exe). 
I would like to bind specific shortcuts specifically when I'm using animebook like: Space "Pause/Play", Enter "Replay caption", Left/Right "Move backward/forward" and so on. But I couldn't find a specific identification for animebook since the name will change depending on what I'm watching.
![image](https://user-images.githubusercontent.com/35316996/147397794-e19d493f-95fe-496b-bc54-a5f019ab06a9.png)
The reason why I bind on my mouse is to chill with one hand and also be able to use yomichan where Alt is already bound on my mouse when navigating with Chrome to scan kanjis.

**Comment by soameshi** [comment]
Yeah that'd be fine. Mind if I put it at the end of the tab name though? I like having the episode number (if it can find it) be the first thing visible in the tab so it's easier for me to remember what episode I'm on.

**Comment by Hiwoyn** [comment]
Yes at the end it's great, I can use $ to tell ahk to look at the end of the name.

**Comment by soameshi** [comment]
Cool. Updated, so feel free to try it out.

**Comment by Hiwoyn** [comment]
![image](https://user-images.githubusercontent.com/35316996/147489147-b584d988-bee7-4c9e-a7ef-9a9b3f2353d2.png)
Perfect, thank you.
