### ISSUE TITLE
[Feature Request] Hide Parenthesis

### ISSUE THREAD

**Issue by cademcniven** [animebook/animebook.github.io#47]
I think it'd be useful to be able to optionally hide parenthesis (and the things inside them) in subtitles. 
![image](https://user-images.githubusercontent.com/17060136/153765547-90d742e3-a086-439e-8a59-4661e0cfaade.png)
Generally they either show who is talking, or contain furigana (which doesn't display correctly). This not only makes it harder to read, but it also prevents some words from being scanned with yomichan, because the furigana parenthesis are placed in the middle of the word

**Comment by c-ehrlich** [comment]
You can create a regex in Yomichan to have it ignore things inside parentheses. Nonetheless I agree that this would be a good feature.

![Yomichan setting](https://cdn.discordapp.com/attachments/797748730807320588/811988186054131732/unknown.png)

**Comment by soamsy** [comment]
This has been added. The hotkey to hide parens is 'h', and the regex to hide them can be customized in the new 'Appearance' menu.
