### ISSUE TITLE
[Bug] Error message with certain video types

### ISSUE THREAD

**Issue by msw93** [animebook/animebook.github.io#48]
It seems that the extension has issues with certain video types. When I try to export the sentence to I get the following error message.

![image](https://user-images.githubusercontent.com/4367703/156689508-b354f9e0-688a-44e1-b986-e6b3364e5303.png)

I think this is likely due to the video type because of error message?

I've also tried using same srt with different video file and its no problem. Here is this videos codec info!
![image](https://user-images.githubusercontent.com/4367703/156689832-f630aa88-47bc-4251-a1d8-b2adc4b53cc4.png)

**Comment by soamsy** [comment]
There's a still jpg embedded into the video as an MJPG that animebook's ffmpeg is seeing and trying to use incorrectly. It looks like a BD cover.
![image](https://user-images.githubusercontent.com/20632064/156697004-48ac8fd4-b60b-4b14-8618-bb159f9909af.png)

For a quick fix, you should get rid of the MPEG stream 1 from the files you converted. One way I know how to do this is to copy every stream that isn't stream 1 using ffmpeg's -map option.
```
ffmpeg -i {INPUT}.mkv -map 0:0 -map 0:2 -map 0:3 {OUTPUT}.mkv
```
Note how there isn't a -map 0:1

**Comment by soamsy** [comment]
And weirdly enough, I couldn't reproduce this until I converted the video's JP audio to aac. When I used the original video (which oddly enough uses aac for English) I could still make English audio flashcards, despite the MJPG still being there. It might have to do with the 'duration' field disappearing when these videos get run through your conversion script, since the MJPG technically had a duration of like 1/100 of a second before conversion.

**Comment by msw93** [comment]
I forgot to mention that I converted the files 🤣, good catch

I think you command you sent works, but its so slow on my computer 😞 

![image](https://user-images.githubusercontent.com/4367703/156701468-b17fbfba-4183-4c8f-a6bf-4943aa70e72d.png)

**Comment by msw93** [comment]
I think I figured everything out and I hate myself because its almost 1am lol

I used this aac.bat script to convert original video file `FOR %%i IN (%*) DO ffmpeg -i "%%~fi" -map 0:v -map 0:a -c:v copy -c:a aac "%%~di%%~pi%%~ni_converted%%~xi"`

This adds the shitty bluray cover in ffmpeg's auto mapping. Switching over to your command was too slow but if I specify the codec to be `copy` it only takes seconds.

`ffmpeg -i {converted_output}.mkv -map 0:0 -map 0:a -c:v copy -c:a copy {input}.mkv`

Here is output codec, of the twice converted file.
![image](https://user-images.githubusercontent.com/4367703/156707185-98525ada-4dec-4efe-bbeb-2b137a708d38.png)

and the speed
![image](https://user-images.githubusercontent.com/4367703/156707266-3f8396b5-9970-4664-b4ac-748f1579f771.png)

**Comment by soamsy** [comment]
Congrats, and sorry about that 🙃

I was only testing with one file, so I didn't realize putting -c:v copy -c:a copy would make it faster. Good to know.
