### ISSUE TITLE
 How do you center movies that are not 16:9? 

### ISSUE THREAD

**Issue by Dan9922** [animebook/animebook.github.io#49]
Eg:
![chrome_d6BO0OdikC](https://user-images.githubusercontent.com/103450077/162798369-1a7603c5-8ca0-48dd-95cd-76b7caeef188.jpg)

**Comment by soamsy** [comment]
Added a setting to change the vertical alignment of where the video player is. Try it out if you get the chance
![chrome_2022-08-22_16-40-28](https://user-images.githubusercontent.com/20632064/186031535-5a661e46-daf1-4586-918e-7b98a50a79b6.jpg)
.
