### ISSUE TITLE
HEVC/H265 for Microsoft Edge.

### ISSUE THREAD

**Issue by avc1657** [animebook/animebook.github.io#57]
Today I found an extension here on GitHub that tweaks Edge to enable its already existent (but hidden) HEVC support: https://github.com/jlnsrk/h265ify

The extension requires HEVC installed on Windows. From MS Store you need to pay for it (if I'm not mistaken). But there're also free standalone installers that you can find here: https://www.free-codecs.com/hevc_video_extension_download.htm (I have version 2.0.51121 x64 installed. The first link should be for 32-bit systems).

Ok so I tested the extension and the result is: yeah it works. Well... Idk about any instabilities or something, just know from a quick test that it works. A good feature of Edge is its AC3 and E-AC3 support, which is great.

Edit: I forgot to test if HEVC videos still work without the browser extension. A couple months ago I tried to run HEVC videos on Edge just with HEVC installed on Windows. HEVC videos would load but the lag during playback was huge.

Edit2: after completely removing the browser extension and restarting it with (chrome://restart), HEVC videos still play normally (idk why :3), but now https://html5test.com/ says HEVC is not supported by the browser. When the extension is installed the html5 tester says Edge is compatible with HEVC.

**Comment by soamsy** [comment]
There's been some changes to the Chromium ecosystem recently (most notably support for HEVC video if your hardware supports it), and the Chromium build I recommend in the docs now supports AC3 and E-AC3. I kinda shy away from recommending sketchy downloads, and with the use case for Edge more covered by Chromium now, I think I'll leave its honorable mention in the tips page mostly as is.

Also I did notice the lag in default Edge with HEVC. That's definitely still there.
