### ISSUE TITLE
[Feature Request] An audio toggle for Anki context addition

### ISSUE THREAD

**Issue by temccarthy** [animebook/animebook.github.io#59]
When I add subtitle context to an anki card, the context audio is autoplayed when the screenshot appears in the bottom right corner to signify that the card has been added. It would be great if you could toggle that audio on or off so I don't have to wait for the card to load, then the audio to play before resuming watching my show.

**Comment by soamsy** [comment]
You can turn off the audio autoplaying with this option in the settings.

![brave_2022-09-03_02-04-47](https://user-images.githubusercontent.com/20632064/188262024-f296e16c-9c62-4fe9-a646-928f5392dd90.jpg)
