### ISSUE TITLE
Subtitles not showing in fullscreen

### ISSUE THREAD

**Issue by deliana-d** [animebook/animebook.github.io#75]
When I switch to fullscreen mode, the subtitles disappear (tested on Chrome 109.0.5414.121 (Official Build) (64-bit) and Firefox 109.0.1 (64-bit) on Windows 10).

**Comment by soamsy** [comment]
Yeah, this is an issue with how animebook uses the default video player the browser provides. You can get around this by hitting F11 to enter fullscreen mode with your browser instead (you'll also get the sidebar this way, which is nice).

**Comment by deliana-d** [comment]
Oh perfect, thank you. That works great!

Apologies if this had been asked and answered before.
