### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by FirionHope** [animebook/animebook.github.io#81]
Hi, since you recommend using ASB player I'm trying to switch to that. I want to use as similar as subtitle style as possible to the one used on animebook though, I find it very readable. What font does animebook use, and if possible what other settings should I change to match the style of animebooks subtitles?

**Comment by soamsy** [comment]
Both players are using the default CJK font provided by your OS/browser, which in my case on Windows is Meiryo. You may need to set that up in your Chrome/Firefox settings.

For everything else, I'd just play with the ASB "Subtitle Appearance" settings until it looks good. For example, maybe lower the font weight, maybe make the background transparent, etc.
