### ISSUE TITLE
Pressing "t" to switch between audio tracks has suddenly stopped working

### ISSUE THREAD

**Issue by mjauvi** [animebook/animebook.github.io#82]
I tried switching between subtitle tracks on a few episodes of different series', but "t" didn't work on any of them. It has worked for me just fine in the past. This is a big problem since so many files are dual audio, with English being the default. I also tried manually changing the default audio track of my file from English to Japanese, but animebook still always played the English track. I'm on Chrome.

I know this project isn't maintained, but I would love for this to be fixed since this is the main player I use. I often do immersion together with other people so being able to make anki cards quickly without having to re-listen to audio is a huge plus. I completely understand if this cannot be fixed though.

**Comment by soamsy** [comment]
Is the `enable-experimental-web-platform-features` flag in chrome://flags enabled? I believe that's still necessary if you're on chrome. Firefox has a similar flag that has to be enabled.

**Comment by mjauvi** [comment]
Yeah, I have it enabled. I also tested this on both firefox and opera gx and switching audio tracks didn't work on either one. I've also confirmed that the alternate audio tracks do exist, because I can switch between them in asbplayer through the menu just fine.

**Comment by mjauvi** [comment]
Yeah sure. I tried a couple different ones I've had for a while so I don't remember the nyaa links for those, but this one I still had saved. None of the videos from this torrent worked for me (tried like 5 different videos from different folders).
https://nyaa.si/view/1689611

If you need more examples just let me know!

**Comment by mjauvi** [comment]
Oh my god...yeah, that was my problem. I didn't have subtitles added to the video and didn't for a second think that that could affect the hotkeys. I came across this issue while comparing videos from different torrents, so I didn't add subtitles. Funny to think that I had never run into this problem until now

Thank you for the help!
